### ISSUE TITLE
NetworkThroughputTestParameters.remoteHost type issue

### ISSUE THREAD

**Issue by g4gps** [CloudSurgeon/delphixpy-examples#7]
Hi
I am using delphixpy to perform network latency and throughput test 
I was able to achieve latency test.
But i am having problem when i try to perform throughput test. I am not able to throughput.create with input parameter NetworkThroughputTestParameters.
as per API document, NetworkThroughputTestParameters.remoteHost is required, but library demands NetworkThroughputTestParameters.remote_host value. Is there any difference?
I am getting error as below in all 3 different attempts where i am defining remoteHost. Please advice howelse to define required input value remoteHost.
-------attempt1------
network_test_param_objtx.remoteHost = "host1"
try:
    throughput.create(dx_session_obj.server_session,network_test_param_objtx)
ERROR: #'The field "{0}" is required.'
------attempt2------------
hst = Host()
hst.address = "host1"
network_test_param_objtx = NetworkThroughputTestParameters()
network_test_param_objtx.remoteHost = hst 
try:
    throughput.create(dx_session_obj.server_session,network_test_param_objtx)
ERROR: #'The field "{0}" is required.'
--------attempt3-------------------------
network_test_param_objtx = NetworkThroughputTestParameters()
network_test_param_objtx.remote_host = "host1"
try:
    throughput.create(dx_session_obj.server_session,network_test_param_objtx)
ERROR:The provided string "host1" is not a valid object reference.'

**Comment by CloudSurgeon** [comment]
Hey, sorry I am just now seeing this. The python styling guide changes "camelCase" to "under_bar" styling methods. So, API of NetworkThroughputTestParameters.remoteHost results in NetworkThroughputTestParameters.remote_host in python.

Secondly, it wants the host reference, not the host name. So, that would look something more like this:
```
network_test_param_objtx = NetworkThroughputTestParameters()
network_test_param_objtx.remote_host = "UNIX_HOST-1"
try:
throughput.create(dx_session_obj.server_session,network_test_param_objtx)
```

I always use the CLI first to check to see what information should be provided. 
ex.
```
ip-10-0-1-10 network test throughput create *> ls
Properties
    type: NetworkThroughputTestParameters
    blockSize: 128KB
    direction: TRANSMIT
    duration: 30
    numConnections: 0
    port: (unset)
    remoteAddress: (unset)
    remoteHost: (required)
    sendSocketBuffer: 4MB

ip-10-0-1-10 network test throughput create *> set remoteHost=ip-10-0-1-20.us-west-2.compute.internal 
ip-10-0-1-10 network test throughput create *> setopt trace=true
ip-10-0-1-10 network test throughput create *> commit
=== POST /resources/json/delphix/network/test/throughput ===
{
    "type": "NetworkThroughputTestParameters",
    "remoteHost": "UNIX_HOST-1"
}
=== RESPONSE ===
{
    "type": "OKResult",
    "status": "OK",
    "result": "NETWORK_THROUGHPUT_TEST-1",
    "job": "JOB-7",
    "action": "ACTION-29"
}
=== END ===
    NETWORK_THROUGHPUT_TEST-1
    Dispatched job JOB-7
```
