### ISSUE TITLE
python3 compatiliblity

### ISSUE THREAD

**Issue by jgebal** [CloudSurgeon/delphixpy-examples#8]
Hi,
I've noticed that all examples are based on delphixpy 1.8.0 and are compatible with python 2.
Are there any plans/efforts to upgrade to python3 and latest API?

Thanks for the great work on scripting all of the examples.

**Comment by CloudSurgeon** [comment]
Hi! I know my colleague @mcbrune was working on something. I'll ping him to see where he's at.

**Comment by jgebal** [comment]
Thanks.
I think I'm god for now. Can use python 2 ;)

**Comment by CloudSurgeon** [comment]
I'll give @mcbrune  a kick. :) Thanks Jacek

**Comment by jgebal** [comment]
Thanks @CloudSurgeon 
I did try to run the project on python3 but it seems like a bit more work than change of **print** syntax in scripts.

- the `delphixpy` library version is hardcoded to version not compatible with python3 (1.8)
- change of library version doesn't seem to do the trick (were there any breaking changes in library API?)

It seems like I'm a bit stuck after all as in the environment I'm in it ill take quite a bit of effort to have python2 installed (we do have python3).

I might give a try with building my own scripts based on `delphixpy` but your examples seem to be perfect **out of the box slution** to the challenges that I would need to overcome myself otherwise.

**Comment by CloudSurgeon** [comment]
@mcbrune and I might be able to take a run at a couple of them to help get you pointed in the right direction. Are there any specific ones that would really be helpful right now?

**Comment by jgebal** [comment]
`js_bookmark.py` and `js_container.py` are the ones I'm looking into at the moment.
The functionality I need to use is only:
- create, delete, update, share bookmark
- refresh container from dsource
- reset container to bookmark created

The workflow that I'd like to use is:
- deploy changes
- create bookmark
- propagate bookmark to other VDB's
- repeat
- when DSource is updated:
   -  refresh from DSource,
   - deploy, 
   - created new bookmark

**Comment by mcbrune** [comment]
Hello @jgebal 

I'm working on porting this repo to Python3. All of the lib modules are updated and am working on updating the bookmark script now. The first commit of these will be this week but initially will use a different branch - python3-api-1-10-2.

**Comment by jgebal** [comment]
This is amazing news.
Thank you @mcbrune for super fast feedback!

**Comment by jgebal** [comment]
Is this issue resolved?
Python2 is end of life.
