### ISSUE TITLE
Passing credentials

### ISSUE THREAD

**Issue by jgebal** [CloudSurgeon/delphixpy-examples#9]
I know that the examples are all based on config file.
Is there any way to dynamically pass credentials to scripts from command line?
I'd like to avoid storing credentials in config file that can be visible to multiple people.

**Comment by CloudSurgeon** [comment]
Sure. You would just use args. I think you can see in a few of my examples where I use the docopt module to define arguments that can both be passed in as an arg and as a param in a config file. For instance, see here: https://github.com/delphix/delphixpy-examples/blob/master/dx_provision_vdb.py

But, then you run the risk of anyone on the system running a `ps -aux` and seeing the secret argument in the process command. The best practice for secrets is to store your secrets in a secure file that only you have access to reading. Or.... to use something like Vault from Hashicorp to store and pass secrets (but that is beyond the scope of this repo).
